spring.application.name=evcomp


# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Output Formatting
spring.jackson.serialization.indent_output=true
spring.profiles.active=mysql

# Integrações Externas (Lido via variável de ambiente)
resend.api.key=${RESEND_API_KEY}
